version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: financebot-broker
    ports:
      - ${MQTT_PORT}:1883
    volumes:
      - ./mqtt/:/mosquitto/

  worker:
    image: financebot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financebot-worker
    working_dir: /app
    volumes:
      - ./:/app/
    env_file:
      - .env
    hostname: worker
    ports:
      - ${POLYGONBOT_PORT}:${POLYGONBOT_PORT}

  slackbot:
    image: financebot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financebot-slackbot
    working_dir: /app
    volumes:
      - ./:/app/
    env_file:
      - .env
    hostname: slackbot
    ports:
      - ${SLACKBOT_PORT}:${SLACKBOT_PORT}
