version: "3.9"
services:
  mosquitto:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  worker:
    image: financebot-polygonbot:${RELEASE_VERSION}
    restart: always
    command: python3 worker.py
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  slackbot:
    image: financebot-slackbot:${RELEASE_VERSION}
    restart: always
    command: python3 main.py
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"
