version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: financebot-broker
    ports:
      - ${MQTT_PORT}:1883
    volumes:
      - ./mqtt/:/mosquitto/

  polygonbot:
    container_name: polygonbot
    hostname: polygonbot
    ports:
      - ${POLYGONBOT_PORT}:${POLYGONBOT_PORT}

  slackbot:
    container_name: slackbot
    hostname: slackbot
    ports:
      - ${SLACKBOT_PORT}:${SLACKBOT_PORT}
